// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.22.2";

// src/lib/mcp/tools/whoami.ts
import { createClient } from "npm:@supabase/supabase-js@^2.103.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.22.2";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in Deutsch Meister user's id, email, display name, and roles.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const userId = ctx.getUserId();
    const email = ctx.getUserEmail();
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const [{ data: profile }, { data: roles }] = await Promise.all([
      sb.from("profiles").select("display_name, approved").eq("user_id", userId).maybeSingle(),
      sb.from("user_roles").select("role").eq("user_id", userId)
    ]);
    const info = {
      user_id: userId,
      email,
      display_name: profile?.display_name ?? null,
      approved: profile?.approved ?? null,
      roles: (roles ?? []).map((r) => r.role)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-my-classes.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.103.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_my_classes_default = defineTool2({
  name: "list_my_classes",
  title: "List my classes",
  description: "List classes the signed-in user teaches or is enrolled in. Respects row-level security.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("classes").select("id, name, level, sub_level_id, status, start_date, end_date, current_students_count").order("created_at", { ascending: false }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { classes: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-certificates.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.103.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.22.2";
var list_my_certificates_default = defineTool3({
  name: "list_my_certificates",
  title: "List my certificates",
  description: "List certificates issued to the signed-in student. Respects row-level security.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("certificates").select("id, certificate_number, certificate_kind, final_score, mention, status, issued_at").eq("student_id", ctx.getUserId()).order("issued_at", { ascending: false }).limit(50);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { certificates: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-homework.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.103.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.22.2";
import { z } from "npm:zod@^4.4.3";
var list_my_homework_default = defineTool4({
  name: "list_my_homework",
  title: "List my homework",
  description: "List homework assignments visible to the signed-in user. Respects row-level security.",
  inputSchema: {
    status: z.enum(["all", "open", "closed"]).optional().describe("Filter by status. Defaults to all.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = sb.from("homework").select("id, title, level, category, due_at, status, class_id").order("due_at", { ascending: false, nullsFirst: false }).limit(100);
    if (status && status !== "all") q = q.eq("status", status);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { homework: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "uqyjpvsdiuiuomkoocnk";
var mcp_default = defineMcp({
  name: "deutsch-meister-mcp",
  title: "Deutsch Meister",
  version: "0.1.0",
  instructions: "Read-only tools for the Deutsch Meister learning platform. Callers act as their own signed-in user; row-level security applies to every query.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_my_classes_default, list_my_certificates_default, list_my_homework_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.22.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
