
ALTER TABLE public.question_bank ALTER COLUMN owner_id DROP NOT NULL;

INSERT INTO public.question_bank (source, level, skill, kind, prompt_de, prompt_fr, prompt_ar, options_de, options_fr, options_ar, correct_answer, explanation_fr, explanation_ar, points, is_public, owner_id, tags) VALUES
-- A2
('goethe','A2','grammatik','qcm','Gestern ___ ich ins Kino gegangen.','Hier, je ___ allé(e) au cinéma.','أمس ___ إلى السينما.',
 '["bin","habe","war","ist"]'::jsonb,'["suis","ai","étais","est"]'::jsonb,'["كنتُ","لديّ","ذهبتُ","هو"]'::jsonb,
 '0','Verbe de mouvement → Perfekt avec sein.','أفعال الحركة تستعمل sein في الماضي.',1,true,NULL,ARRAY['perfekt','sein']),
('goethe','A2','wortschatz','qcm','Wie heißt das Gegenteil von "billig"?','Quel est le contraire de "bon marché" ?','ما عكس "رخيص"؟',
 '["teuer","klein","schnell","alt"]'::jsonb,'["cher","petit","rapide","vieux"]'::jsonb,'["غالٍ","صغير","سريع","قديم"]'::jsonb,
 '0','teuer = cher.','teuer = غالٍ.',1,true,NULL,ARRAY['adjectifs']),
('goethe','A2','lesen','qcm','"Ich nehme den Bus, weil mein Auto kaputt ist." Was ist kaputt?','"Je prends le bus parce que ma voiture est en panne." Qu''est-ce qui est en panne ?','ما هو المعطّل؟',
 '["das Auto","der Bus","das Fahrrad","der Zug"]'::jsonb,'["la voiture","le bus","le vélo","le train"]'::jsonb,'["السيارة","الحافلة","الدراجة","القطار"]'::jsonb,
 '0','"mein Auto ist kaputt".','"سيارتي معطّلة".',1,true,NULL,ARRAY['compréhension']),
('oesd','A2','hoeren','audio','Hören Sie: "Der Zug nach Wien fährt um 14:30 von Gleis 5 ab."','Écoutez : à quelle heure part le train ?','استمع: متى ينطلق القطار؟',
 '["14:30","15:30","13:40","14:13"]'::jsonb,'["14h30","15h30","13h40","14h13"]'::jsonb,'["14:30","15:30","13:40","14:13"]'::jsonb,
 '0','"um 14:30".','الساعة 14:30.',2,true,NULL,ARRAY['Bahnhof','Uhrzeit']),
('oesd','A2','grammatik','qcm','Ich helfe ___ Bruder.','J''aide ___ frère.','أساعد ___ أخي.',
 '["meinem","meinen","mein","meines"]'::jsonb,'["mon (datif)","mon (acc.)","mon","de mon"]'::jsonb,'["لأخي","أخي(منصوب)","أخي","لأخي(مضاف)"]'::jsonb,
 '0','helfen + Dativ → meinem.','الفعل helfen يطلب الـDativ.',1,true,NULL,ARRAY['dativ']),
('goethe','A2','schreiben','translate','Übersetze: "Ich möchte einen Kaffee bitte."','Traduis : "Je voudrais un café s''il vous plaît."','ترجم: "أريد قهوة من فضلك."',
 NULL,NULL,NULL,
 'Je voudrais un café s''il vous plaît.','Formule polie.','صيغة مهذّبة.',2,true,NULL,ARRAY['restaurant']),
('goethe','A2','wortschatz','qcm','Welcher Tag kommt nach Mittwoch?','Quel jour vient après mercredi ?','أي يوم يأتي بعد الأربعاء؟',
 '["Donnerstag","Dienstag","Freitag","Samstag"]'::jsonb,'["jeudi","mardi","vendredi","samedi"]'::jsonb,'["الخميس","الثلاثاء","الجمعة","السبت"]'::jsonb,
 '0','Mittwoch → Donnerstag.','الأربعاء → الخميس.',1,true,NULL,ARRAY['Wochentage']),
('oesd','A2','schreiben','write','Schreiben Sie 30 Wörter über Ihre Familie.','Écris 30 mots sur ta famille.','اكتب 30 كلمة عن عائلتك.',
 NULL,NULL,NULL,
 '(évalué par le professeur)','Production écrite simple.','إنتاج كتابي بسيط.',5,true,NULL,ARRAY['Familie']),

-- B1
('goethe','B1','grammatik','qcm','Wenn ich Zeit ___, würde ich nach Berlin reisen.','Si j''___ du temps, je voyagerais à Berlin.','لو ___ وقت، لسافرتُ إلى برلين.',
 '["hätte","habe","hatte","haben"]'::jsonb,'["avais","ai","avais (passé)","avons"]'::jsonb,'["كان لديّ","لديّ","كان لديّ","لدينا"]'::jsonb,
 '0','Konjunktiv II : hätte.','صيغة الشرط Konjunktiv II.',2,true,NULL,ARRAY['konjunktiv2']),
('goethe','B1','lesen','qcm','"Trotz des Regens gingen wir spazieren." Warum?','"Malgré la pluie, nous nous sommes promenés." Pourquoi ?','لماذا تنزّهوا؟',
 '["Sie wollten trotzdem","Wegen Regens","Es war sonnig","Sie hatten Termin"]'::jsonb,'["Ils voulaient quand même","À cause de la pluie","Il faisait soleil","Ils avaient RDV"]'::jsonb,'["أرادوا رغم ذلك","بسبب المطر","كانت مشمسة","كان لديهم موعد"]'::jsonb,
 '0','"trotz" = concession.','trotz تفيد التنازل.',2,true,NULL,ARRAY['konjunktionen']),
('oesd','B1','hoeren','audio','Hören Sie: "Die Vorlesung beginnt am Montag um neun Uhr im Hörsaal B."','Écoute et choisis l''info correcte.','استمع واختر الإجابة الصحيحة.',
 '["Montag 9:00 Hörsaal B","Sonntag 9:00 Hörsaal A","Montag 19:00 Hörsaal B","Mittwoch 9:00 Hörsaal C"]'::jsonb,'["lundi 9h salle B","dimanche 9h salle A","lundi 19h salle B","mercredi 9h salle C"]'::jsonb,'["الإثنين 9:00 قاعة B","الأحد 9:00 قاعة A","الإثنين 19:00 قاعة B","الأربعاء 9:00 قاعة C"]'::jsonb,
 '0','"Montag um neun".','الإثنين الساعة 9.',2,true,NULL,ARRAY['Universität']),
('oesd','B1','grammatik','qcm','Das ist der Mann, ___ ich gestern getroffen habe.','C''est l''homme ___ j''ai rencontré hier.','هذا هو الرجل ___ قابلتُه أمس.',
 '["den","der","dem","dessen"]'::jsonb,'["que (acc.)","qui (nom.)","à qui (dat.)","dont"]'::jsonb,'["الذي(مفعول)","الذي(فاعل)","الذي(غير مباشر)","الذي(مضاف)"]'::jsonb,
 '0','Akkusativ-Relativpronomen : den.','الضمير الموصول في Akkusativ.',2,true,NULL,ARRAY['relativsätze']),
('goethe','B1','schreiben','translate','Übersetze: "Obwohl es regnete, sind wir spazieren gegangen."','Traduis cette phrase en français.','ترجم الجملة إلى الفرنسية.',
 NULL,NULL,NULL,
 'Bien qu''il pleuve, nous sommes allés nous promener.','obwohl = bien que.','obwohl = رغم أن.',3,true,NULL,ARRAY['konjunktionen']),
('goethe','B1','schreiben','write','Schreiben Sie eine E-Mail (80 Wörter), in der Sie sich für ein Praktikum bewerben.','Rédige un e-mail (80 mots) de candidature pour un stage.','اكتب بريداً (80 كلمة) للترشّح لتدريب.',
 NULL,NULL,NULL,
 '(évalué par le professeur)','Demande formelle.','طلب رسمي.',5,true,NULL,ARRAY['Brief']),
('oesd','B1','wortschatz','qcm','Was bedeutet "umweltfreundlich"?','Que signifie "umweltfreundlich" ?','ماذا تعني "umweltfreundlich"؟',
 '["respektvoll zur Umwelt","unfreundlich","umgebaut","umsonst"]'::jsonb,'["respectueux de l''environnement","peu aimable","reconstruit","gratuit"]'::jsonb,'["صديق للبيئة","غير ودود","معاد البناء","مجاني"]'::jsonb,
 '0','Umwelt = environnement.','Umwelt = البيئة.',1,true,NULL,ARRAY['Umwelt']),

-- B2
('goethe','B2','grammatik','qcm','Das Haus wurde im 19. Jahrhundert ___.','La maison ___ au XIXᵉ siècle.','المنزل ___ في القرن 19.',
 '["gebaut","bauen","baute","gebauten"]'::jsonb,'["a été construit","construire","construisit","construites"]'::jsonb,'["تم بناؤه","يبني","بنى","المبنية"]'::jsonb,
 '0','Passiv Präteritum.','المبني للمجهول في الماضي.',2,true,NULL,ARRAY['passiv']),
('goethe','B2','lesen','qcm','"Die Studie zeigt, dass die Digitalisierung Arbeitsplätze schafft, aber auch vernichtet." Welche Aussage stimmt?','Quelle affirmation correspond ?','أي عبارة تطابق النص؟',
 '["Beides: schafft und vernichtet","Nur Verluste","Nur Gewinne","Keine Veränderung"]'::jsonb,'["Les deux à la fois","Que des pertes","Que des gains","Aucun changement"]'::jsonb,'["الاثنان معاً","خسائر فقط","مكاسب فقط","لا تغيير"]'::jsonb,
 '0','"schafft, aber auch vernichtet".','يخلق ويُبيد.',3,true,NULL,ARRAY['Wirtschaft']),
('oesd','B2','grammatik','qcm','Er behauptete, er ___ krank gewesen.','Il a affirmé qu''il ___ malade.','ادّعى أنه ___ مريضاً.',
 '["sei","ist","war","wäre"]'::jsonb,'["soit (KI)","est","était","serait"]'::jsonb,'["كان (KI)","هو","كان","سيكون"]'::jsonb,
 '0','Konjunktiv I (Indirekte Rede).','الكلام غير المباشر.',2,true,NULL,ARRAY['konjunktiv1']),
('oesd','B2','hoeren','audio','Hören Sie: "Die Inflationsrate ist um 2,3 Prozent gestiegen."','Écoute et choisis le chiffre correct.','استمع واختر النسبة الصحيحة.',
 '["2,3%","3,2%","23%","0,23%"]'::jsonb,'["2,3 %","3,2 %","23 %","0,23 %"]'::jsonb,'["2.3٪","3.2٪","23٪","0.23٪"]'::jsonb,
 '0','"um 2,3 Prozent gestiegen".','ارتفعت بنسبة 2.3٪.',2,true,NULL,ARRAY['Wirtschaft']),
('goethe','B2','schreiben','translate','Übersetze: "Trotz aller Schwierigkeiten gab er nicht auf."','Traduis en français.','ترجم إلى الفرنسية.',
 NULL,NULL,NULL,
 'Malgré toutes les difficultés, il n''a pas abandonné.','aufgeben = abandonner.','aufgeben = يستسلم.',3,true,NULL,ARRAY['Verben']),
('goethe','B2','schreiben','write','Schreiben Sie einen Kommentar (180 Wörter): "Soziale Medien: Chance oder Gefahr?".','Rédige un commentaire (180 mots).','اكتب تعليقاً (180 كلمة).',
 NULL,NULL,NULL,
 '(évalué par le professeur)','Argumentation structurée.','حجاج منظّم.',8,true,NULL,ARRAY['Diskussion']),
('oesd','B2','wortschatz','qcm','Was bedeutet "nachhaltig"?','Que signifie "nachhaltig" ?','ماذا تعني "nachhaltig"؟',
 '["dauerhaft, ressourcenschonend","kurzfristig","laut","schnell"]'::jsonb,'["durable, écologique","à court terme","bruyant","rapide"]'::jsonb,'["مستدام","قصير الأمد","صاخب","سريع"]'::jsonb,
 '0','Nachhaltigkeit = durabilité.','الاستدامة.',2,true,NULL,ARRAY['Umwelt']),
('goethe','B2','sprechen','speak','Sprechen Sie 90 Sekunden über Vor-/Nachteile von Homeoffice.','Parle 90 sec. des avantages/inconvénients du télétravail.','تحدث 90 ثانية عن مزايا وعيوب العمل عن بُعد.',
 NULL,NULL,NULL,
 '(évalué par le professeur)','Production orale.','إنتاج شفوي.',6,true,NULL,ARRAY['Beruf']);
